### PR TITLE
Add initial tree support

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by mikanIchinose** [comment]
I found a strange open action behavior.

```vim
" minimal setting
set runtimepath^=path/to/denops.vim
set runtimepath^=path/to/ddu.vim
set runtimepath^=path/to/ddu-kind-file
set runtimepath^=path/to/ddu-ui-filer
set runtimepath^=path/to/ddu-source-markdown

augroup Ddu
  autocmd!
  autocmd FileType ddu-filer nnoremap <buffer> q <Cmd>call ddu#ui#filer#do_action('quit')<CR>
  autocmd FileType ddu-filer nnoremap <buffer> o <Cmd>call ddu#ui#filer#do_action('expandItem',{'mode': 'toggle'})<CR>
  autocmd FileType ddu-filer nnoremap <buffer> <CR> <Cmd>call ddu#ui#filer#do_action('itemAction')<CR>
augroup END

call ddu#custom#patch_global({
      \ 'sources': [{'name': 'markdown'}],
      \ 'ui': 'filer',
      \ 'kindOptions': {'file': {'defaultAction': 'open'}},
      \ })
```

https://user-images.githubusercontent.com/29175998/198830539-abe83f83-9a65-4782-97f0-41fd6517fb21.mov

**Comment by Shougo** [comment]
Please test the latest plugins.  I think the problems are fixed.

**Comment by mikanIchinose** [comment]
When I use ddu-ui-ff, it is almost expected to open header.

But sometimes duplicate header by call `ddu#ui#ff#do_action('expandItem', {'mode': 'toggle'})`

I expected it is caused by the last tree.

https://user-images.githubusercontent.com/29175998/198929467-412b5f8c-d398-45f2-958b-a87dfd197cb2.mov

**Comment by Shougo** [comment]
Please upload the markdown file.  I will test it.

**Comment by Shougo** [comment]
Please upload the instruction.

**Comment by Shougo** [comment]
Reproduced.  I have fixed the problem.  Please update UI plugins.

**Comment by Shougo** [comment]
Thanks.

**Pull request merged**
